export const chatsData = [
  {
    id: 1,
    username: 'ABC test1',
    avatar: '1',
    avatarColor: '#128C7E',
    lastMessage: 'Hey, how are you?',
    time: '10:30 AM',
    online: true,
    messages: [
      { id: 1, text: 'Hey, how are you?', sender: 'them', time: '10:30 AM' },
      { id: 2, text: 'I\'m good, you?', sender: 'me', time: '10:31 AM' },
      { id: 3, text: 'Doing great! See you later', sender: 'them', time: '10:32 AM' },
    ],
  },
  {
    id: 2,
    username: 'ABC test2',
    avatar: '2',
    avatarColor: '#E1306C',
    lastMessage: 'That looks amazing!',
    time: '9:15 AM',
    online: false,
    messages: [
      { id: 1, text: 'Check out my new painting!', sender: 'them', time: '9:15 AM' },
      { id: 2, text: 'That looks amazing!', sender: 'me', time: '9:16 AM' },
    ],
  },
  {
    id: 3,
    username: 'ABC test3',
    avatar: '3',
    avatarColor: '#075E54',
    lastMessage: 'Are we still on for today?',
    time: '8:00 AM',
    online: true,
    messages: [
      { id: 1, text: 'Are we still on for today?', sender: 'them', time: '8:00 AM' },
      { id: 2, text: 'Yes, see you at 5!', sender: 'me', time: '8:05 AM' },
      { id: 3, text: 'Perfect, see you then', sender: 'them', time: '8:06 AM' },
    ],
  },
  {
    id: 4,
    username: 'ABC test4',
    avatar: '4',
    avatarColor: '#833AB4',
    lastMessage: 'Haha that\'s hilarious',
    time: '7:30 AM',
    online: false,
    messages: [
      { id: 1, text: 'Check out this meme!', sender: 'them', time: '7:30 AM' },
      { id: 2, text: 'Haha that\'s hilarious ', sender: 'me', time: '7:35 AM' },
    ],
  },
  {
    id: 5,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  },
  {
    id: 6,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  },
  {
    id: 7,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  },
  {
    id: 8,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  },
  {
    id: 9,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  },
  {
    id: 10,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  },
  {
    id: 11,
    username: 'ABC test5',
    avatar: '5',
    avatarColor: '#FD1D1D',
    lastMessage: 'Happy Birthday!',
    time: 'Yesterday',
    online: false,
    messages: [
      { id: 1, text: 'Happy Birthday!', sender: 'them', time: 'Yesterday' },
      { id: 2, text: 'Thank you so much!', sender: 'me', time: 'Yesterday' },
    ],
  }

];
